"""The Today screen, S6. The hero figure, the month, Shop Money and what needs the seller.

Every figure here is either the Money calculator for a period or a count read live from
the tables. Nothing is estimated in this file. The rules below were decided by the owner on
24 September 2026, because DSH-1, DSH-2 and DSH-10 left them open.

**Labels follow A8.** The hero is `gross_profit_after_returns` when every product sold
today has a cost, and `net_proceeds` otherwise. A8 withdrew both "You keep" and "Left after
TikTok", so neither appears. The value is null only if the calculator cannot produce the
figure the label names.

**The day is Europe/London.** A5 defines Today as the current local date in Europe/London
from midnight to the as-at time. The month is the calendar month that day falls in.

**Shop Money covers all time.** It is a settlement position rather than a sales figure,
and a calendar period would cut orders away from their own settlements. Generated is the
same net proceeds the calculator reaches, over every ledger entry the shop holds. Paid out
is the part of it on entries TikTok has settled, which carry a `settlement_id`. Awaiting is
the rest, broken down by the order's status in `order_settlements`, which holds TikTok's
own sub-statuses. Paid out plus awaiting equals generated by construction, which is LED-4.

**Stale** is true when the last successful sync is more than 24 hours old, or when the shop
has never synced. The owner also ruled a 6 to 24 hour "getting old" warning, and the
contract has no field that can carry it, so it is not served. That is a contract gap.

**Needs you** is counted live from the tables on every request. It is ordered critical,
then warning, then info, then by the amount at stake, then by count. The owner ruled that
a recency tie-break comes last. These items are counts rather than events, so they have no
single time, and the tie-break is by count instead. The severities are:

| Item | Severity | Source |
|---|---|---|
| `connection_action_required` | critical | Ruled. The token has expired, the refresh token has expired, access was revoked, or the shop needs reconnecting |
| `connection_expiring` | warning | Ruled. The refresh token lapses within 14 days. Nothing refreshes a token yet (A23.4), so continuity cannot be guaranteed |
| `stale_data` | warning | Ruled. The last sync is more than 24 hours old |
| `missing_costs` | info | Ruled |
| `first_sync_pending` | info | Ruled |
| `open_discrepancies` | warning | **Derived**, not ruled item by item. A stated amount disagrees with ours, so the figures may be unreliable, which is the owner's definition of a warning |
| `unmapped_fees` | warning | **Derived**. The amounts are in the totals under no named line, so the figures are incomplete |
| `returns_to_check` | warning | **Derived**. Until a return is checked, its stock and any write-off are unknown |
| `out_of_stock` | info | **Derived**. It is operational rather than financial, and it breaks no figure |

Three conditions the owner ruled on have no source in the schema, so they are not served.
They are a required scope that is missing, a refresh that failed, and a partial or
repeatedly failing sync. Nothing in the database records any of them yet.

**Verified by the smoke test only.** The queries were run on the development branch, as
recorded in the pull request. The handler itself has not run against a real database.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Annotated, Any
from uuid import UUID
from zoneinfo import ZoneInfo

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel

from .auth import Account, require_account
from .db import tenant
from .money import Money, money
from .money_view import TIKTOK_FEES, calculate
from .shops import require_shop

router = APIRouter(tags=["Money"])

LONDON = ZoneInfo("Europe/London")
STALE_AFTER = timedelta(hours=24)
EXPIRING_WITHIN = timedelta(days=14)
SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}
AWAITING_STATUSES = ("waiting_delivery", "waiting_return_refund", "delivered_awaiting_settlement")

# The categories whose sum is net proceeds, as the calculator defines it.
NET_PROCEEDS_CATEGORIES = ("gross_sales", "seller_discount", "refund") + TIKTOK_FEES

SHOP_MONEY_SQL = """
select case when le.settlement_id is not null then 'settled'
            else coalesce(os.status, 'unknown') end as status,
       sum(le.amount_minor) as amount_minor,
       count(distinct le.order_id) as orders,
       coalesce(max(le.currency), 'GBP') as currency
  from ledger_entries le
  left join order_settlements os on os.order_id = le.order_id
 where le.shop_id = %(shop)s
   and le.category = any(%(np)s)
 group by 1
"""

NEEDS_YOU_SQL = """
select
  (select count(*) from return_items
    where shop_id = %(shop)s and seller_check_status = 'pending') as returns_to_check,
  (select count(*) from discrepancies
    where shop_id = %(shop)s and status = 'open') as open_discrepancies,
  (select count(*) from stock_positions
    where shop_id = %(shop)s and on_shelf <= 0) as out_of_stock,
  (select count(distinct le.sku_id) from ledger_entries le
    where le.shop_id = %(shop)s and le.category = 'gross_sales' and le.sku_id is not null
      and not exists (select 1 from product_costs pc
                       where pc.sku_id = le.sku_id and pc.superseded_at is null)) as missing_costs,
  (select count(*) from ledger_entries
    where shop_id = %(shop)s and category = 'unmapped_fee'
      and basis_day >= %(month_start)s and basis_day <= %(today)s) as unmapped_fees,
  (select coalesce(-sum(amount_minor), 0) from ledger_entries
    where shop_id = %(shop)s and category = 'unmapped_fee'
      and basis_day >= %(month_start)s and basis_day <= %(today)s) as unmapped_fee_minor,
  (select last_synced_at from shops where id = %(shop)s) as last_synced_at,
  (select connection_status from shops where id = %(shop)s) as connection_status,
  (select access_expires_at from tiktok_connections where shop_id = %(shop)s) as access_expires_at,
  (select refresh_expires_at from tiktok_connections where shop_id = %(shop)s) as refresh_expires_at,
  (select revoked_at from tiktok_connections where shop_id = %(shop)s) as revoked_at,
  (select count(*) from tiktok_connections where shop_id = %(shop)s) as connections
"""


class Hero(BaseModel):
    label: str
    value: Money | None = None
    confidence: str
    cost_coverage: float


class Month(BaseModel):
    period: dict[str, Any]
    gross: Money
    net_proceeds: Money
    kept: Money | None = None
    kept_reason: str | None = None


class Awaiting(BaseModel):
    status: str
    amount: Money
    orders: int


class ShopMoney(BaseModel):
    generated: Money
    paid_out: Money
    awaiting: Money
    awaiting_breakdown: list[Awaiting]


class NeedsYouItem(BaseModel):
    type: str
    count: int
    severity: str
    label: str | None = None
    amount_at_stake: Money | None = None
    href: str | None = None


class TodayView(BaseModel):
    as_of: datetime
    stale: bool
    hero: Hero
    month: Month
    shop_money: ShopMoney
    needs_you: list[NeedsYouItem]


def _plural(n: int, one: str, many: str) -> str:
    return f"{n} {one if n == 1 else many}"


def _needs_you(r: dict[str, Any], now: datetime, currency: str) -> tuple[bool, list[NeedsYouItem]]:
    items: list[NeedsYouItem] = []

    def add(kind: str, count: int, severity: str, label: str, at_stake: int | None = None):
        if count > 0:
            items.append(NeedsYouItem(
                type=kind, count=count, severity=severity, label=label,
                amount_at_stake=money(at_stake, currency) if at_stake else None,
            ))

    # The connection. Ruled by the owner on 24 September 2026.
    if r["connections"]:
        broken = (
            r["revoked_at"] is not None
            or r["connection_status"] in ("needs_reconnect", "disconnected")
            or (r["access_expires_at"] is not None and r["access_expires_at"] <= now)
            or (r["refresh_expires_at"] is not None and r["refresh_expires_at"] <= now)
        )
        if broken:
            add("connection_action_required", 1, "critical",
                "Your TikTok Shop needs reconnecting")
        elif (r["refresh_expires_at"] is not None
              and r["refresh_expires_at"] - now <= EXPIRING_WITHIN):
            days = max((r["refresh_expires_at"] - now).days, 0)
            add("connection_expiring", 1, "warning",
                f"Your TikTok connection expires in {_plural(days, 'day', 'days')}")

    last = r["last_synced_at"]
    stale = last is None or now - last > STALE_AFTER
    if last is None:
        add("first_sync_pending", 1, "info", "Your first sync has not finished yet")
    elif stale:
        hours = int((now - last).total_seconds() // 3600)
        add("stale_data", 1, "warning",
            f"Figures may be out of date. Last synced {hours} hours ago")

    add("open_discrepancies", int(r["open_discrepancies"]), "warning",
        _plural(int(r["open_discrepancies"]), "figure disagrees with TikTok",
                "figures disagree with TikTok"))
    add("unmapped_fees", int(r["unmapped_fees"]), "warning",
        _plural(int(r["unmapped_fees"]), "fee this month has no category",
                "fees this month have no category"),
        int(r["unmapped_fee_minor"]))
    add("returns_to_check", int(r["returns_to_check"]), "warning",
        _plural(int(r["returns_to_check"]), "return to check", "returns to check"))
    add("missing_costs", int(r["missing_costs"]), "info",
        _plural(int(r["missing_costs"]), "product variant has no cost",
                "product variants have no cost"))
    add("out_of_stock", int(r["out_of_stock"]), "info",
        _plural(int(r["out_of_stock"]), "product variant is out of stock",
                "product variants are out of stock"))

    items.sort(key=lambda i: (
        SEVERITY_ORDER[i.severity],
        -(i.amount_at_stake.amount_minor if i.amount_at_stake else 0),
        -i.count,
    ))
    return stale, items


@router.get("/shops/{shopId}/today", response_model=TodayView)
def get_today(
    account: Annotated[Account, Depends(require_account)],
    shop_id: Annotated[UUID, Depends(require_shop)],
    basis: Annotated[str, Query(pattern="^(sales|cash)$")] = "sales",
) -> TodayView:
    now = datetime.now(timezone.utc)
    today = now.astimezone(LONDON).date()
    month_start = today.replace(day=1)

    with tenant(account.id) as conn:
        day = calculate(conn, shop_id, today, today, basis)
        month = calculate(conn, shop_id, month_start, today, basis)

        cur = conn.execute(SHOP_MONEY_SQL, {"shop": str(shop_id),
                                            "np": list(NET_PROCEEDS_CATEGORIES)})
        cols = [d.name for d in cur.description]
        settlement = [dict(zip(cols, r)) for r in cur.fetchall()]

        cur = conn.execute(NEEDS_YOU_SQL, {"shop": str(shop_id),
                                           "month_start": month_start, "today": today})
        cols = [d.name for d in cur.description]
        needs = dict(zip(cols, cur.fetchone()))

    currency = month.totals.net_proceeds.currency

    # The hero. A8's labels, and the figure the label names.
    complete = day.cost_coverage == 1.0
    gpar = day.totals.gross_profit_after_returns
    hero = Hero(
        label="gross_profit_after_returns" if complete else "net_proceeds",
        value=gpar if complete else day.totals.net_proceeds,
        confidence=day.confidence,
        cost_coverage=day.cost_coverage,
    )

    paid = sum(int(s["amount_minor"]) for s in settlement if s["status"] == "settled")
    waiting = [s for s in settlement if s["status"] != "settled"]
    shop_money = ShopMoney(
        generated=money(sum(int(s["amount_minor"]) for s in settlement), currency),
        paid_out=money(paid, currency),
        awaiting=money(sum(int(s["amount_minor"]) for s in waiting), currency),
        # Only TikTok's own sub-statuses are listed, as the contract requires. An unsettled
        # entry whose order has no settlement row counts towards `awaiting` but cannot be
        # given a status, so the breakdown can then sum to less than the total. None exists
        # on the development branch.
        awaiting_breakdown=[
            Awaiting(status=s["status"], amount=money(int(s["amount_minor"]), currency),
                     orders=int(s["orders"]))
            for s in sorted(waiting, key=lambda s: s["status"])
            if s["status"] in AWAITING_STATUSES
        ],
    )

    stale, items = _needs_you(needs, now, currency)

    return TodayView(
        as_of=now,
        stale=stale,
        hero=hero,
        month=Month(
            period=month.period,
            gross=month.totals.gross_sales,
            net_proceeds=month.totals.net_proceeds,
            kept=month.kept,
            kept_reason=month.kept_reason,
        ),
        shop_money=shop_money,
        needs_you=items,
    )
